spring.application.name=spring-ai-ollama-mcp-webmvc

server.port=8088

## 터미널 컬러 출력 설정
spring.output.ansi.enabled=ALWAYS

## SSE 방식의 MCP Server 설정
spring.ai.mcp.server.name=spring-ai-ollama-mcp-webmvc
spring.ai.mcp.server.version=0.0.1

spring.ai.mcp.server.protocol=STREAMABLE

spring.ai.mcp.server.streamable-http.mcp-endpoint=/mcp