spring.application.name=spring-ai-ollama-demo

## Base Properties
# Base URL where Ollama API server is running.
spring.ai.ollama.base-url=http://192.168.0.26:11434
#spring.ai.ollama.base-url=http://localhost:11434
# Whether to pull models at startup-time and how.
spring.ai.ollama.init.pull-model-strategy=never
# How long to wait for a model to be pulled.
spring.ai.ollama.init.timeout=30m
# Maximum number of retries for the model pull operation.
spring.ai.ollama.init.max-retries=0
# Include this type of models in the initialization task.
spring.ai.ollama.init.chat.include=true
# Additional models to initialize besides the ones configured via default properties.
spring.ai.ollama.init.chat.additional-models=[]

## Chat Properties
# Enable Ollama chat model.
spring.ai.model.chat=ollama
# The name of the supported model to use.
spring.ai.ollama.chat.model=gemma4:e2b
# The format to return a response in. Accepts either "json" (any JSON structure) or a JSON Schema object (enforced structure). See Structured Outputs for details.
spring.ai.ollama.chat.format=json
# Controls how long the model will stay loaded into memory following the request
spring.ai.ollama.chat.keep_alive=10m
# Controls whether models emit their reasoning trace before the final answer.
spring.ai.ollama.chat.think=medium

## Gemma를 embedding하기 위한 모델로 Gemma3 기준이나 Gemma4에서도 동작함.
spring.ai.ollama.embedding.model=embeddinggemma
# When you enable thinking mode, the chat model processes complex problems step-by-step.
# Spring AI captures this logic and injects it into the message metadata.
# You can access this reasoning trace programmatically or toggle it via configuration properties

## MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/ollama
spring.datasource.driverClassName=org.mariadb.jdbc.Driver
spring.datasource.username=ollama
spring.datasource.password=ollama

spring.ai.vectorstore.mariadb.initialize-schema=true

# Chat Memory
spring.ai.chat.memory.repository.jdbc.initialize-schema=always

# org.mariadb.jdbc.export.MariaDbDataTruncation: (conn=41) Incorrect vector value: '\xF8\xFA\xD1\xBCrG\x10\xBCF\x8F\x17=\xC8L\x05\xBD\x07\xFA\x89;\xA0\xAC\xD9<\\xAE\xA4\xBBz\xD2z\xBD\xCEJt\xBBm\xCC\x05\xBD\x01...' for column `ollama`.`vector_store`.`embedding` at row 1
# Spring AI에서 MariaDB Vector Store 사용 시 발생하는 MariaDbDataTruncation: Incorrect vector value 오류는 데이터베이스에 정의된 벡터 차원 크기(Dimension)와 현재 생성되는 임베딩 모델의 벡터 차원 크기가 서로 일치하지 않아 발생합니다.
# To store and search local text embeddings generated by Google's EmbeddingGemma (300M, 768 dimensions) via Ollama, use MariaDB Vector (native VECTOR data type supported in MariaDB 11.7+ / 11.8 LTS).
spring.ai.vectorstore.mariadb.dimensions=768

## 정적 리소스에 대해 캐시 사용 안 함
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

## Logger
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.spring.ai.ollama=DEBUG
